#ifndef HEADER_GLOBAL_VARIABLES_H
#define HEADER_GLOBAL_VARIABLES_H

#include <QtCore>

extern bool global_variable_debug_mode_status_bool;
extern bool global_variable_debug_encryption_status_bool;
extern bool global_variable_debug_print_on_terminal_bool;
extern bool global_variable_debug_print_in_file_bool;
extern bool global_variable_debug_type_general_bool;
extern bool global_variable_debug_type_conditional_bool;
extern bool global_variable_debug_type_intensive_bool;

const extern QString global_variable_private_var_tmp_Dir_Path_Parent_QString;
const extern QString global_variable_private_var_tmp_Dir_Path_Case_QString;

#endif // HEADER_GLOBAL_VARIABLES_H
